### ISSUE TITLE
Problem in running faers script without indication

### ISSUE THREAD

**Issue by smruti241** [kylechua/faers-toolkit#1]
I am running the faers script for FDA 2020 ASCII files. I have mentioned only drug csv file because i dont need indication. I ran it but I get the error:
Connected to FAERS database.
Parsed ./input/all_drugs.csv
Traceback (most recent call last):
  File "faers.py", line 37, in <module>
    main()
  File "faers.py", line 16, in main
    info = DBHelper.getInfo(c, drugs)
TypeError: getInfo() missing 1 required positional argument: 'indicationmap'
Please let me know the error and how can I resolve this.

**Comment by ejmurray** [comment]
If you look in the folder named input there are two files: one with the drug name and synonym, the second one is a comma separated list of the indications related to the drug. When you are running the faers.py file you should change the file locations to match the ones that you want to use.

```python
    drugs = parse_file("input/etanercept-drug.csv")
    indications = parse_file("input/etanercept-indications.csv")
```
